AWSTemplateFormatVersion: '2010-09-09'
Description: Required resources for the DeepEnforcement application

Resources:
    CandidateBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: deepenforcement-candidates

    ReferenceBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: deepenforcement-reference

    UnmatchedBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: deepenforcement-unmatched

    MatchedBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: deepenforcement-matched
